services:

  embed-server:
    build: .
    container_name: embed-server
    hostname: embed-server
    ports:
      - "5005:5005"
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
